# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.196.0/containers/alpine/.devcontainer/base.Dockerfile

FROM alpine:3.14

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
